print("Hello VC1 ")
print("Hello VC1 ")
print("Hello VC1 to Building Game")
print("Hello VC1 to Building Game")
print("Hello VC1 ")
print("Hello VC1 ")
print("Hello VC1 to Building Game")
print("Hello VC1 to Building Game")
print("Hello VC1 ")
print("Hello VC1 ")
print("Hello VC1 to Building Game")
print("Hello VC1 to Building Game")
print("Hello VC1 ")
print("Hello VC1 ")
print("Hello VC1 to Building Game")
print("Hello VC1 to Building Game")

